# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21f3482098bfe8859ca21ac15673844161d3cd79dac609ef50c2db5f6a4b08d10cabd8f8506aa5d4043fc640a19bd06b0cf5cfae66bdb7f56929a835311b5994

test:
  secret_key_base: 89af93b7b2c95c60a6fb204f6ab73f30ddbc7224fbba9c59e2b144ddf32ece1c16780da9b616fabab206f8dca881c2180a1a2392811b6e766aa338fd29015707

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
